id = "cuneiform"
name = "Cuneiform Language Support"
description = "Syntax highlighting and theming for Cuneiform story files"
version = "1.0.0"
schema_version = 1
authors = ["David Lantrip <david@example.com>"]
repository = "https://github.com/davidlantrip/cuneiform-grammar"
themes = ["themes/*.json"]

# IMPORTANT: For development, we use file:// URL with local path
# For production, change to: repository = "https://github.com/davidlantrip/cuneiform-grammar"
[grammars.cuneiform]
repository = "file:///Users/davidlantrip/repos/cuneiform_grammar"
rev = "4909ee428cffbf5ea721b0b6b86420a9d836f443"